nodes:
  0: NONE
  1: NODE_A
  2: NODE_B
  3: NODE_C
  4: NODE_D
  5: NODE_E
  6: GS
  7: AUX
ptypes:
  0: NONE
  1: REQ
  2: RES
  3: ACK
  4: TLM
  5: FILE
node_descriptions:
  NODE_A: Payload Processor A
  NODE_B: Payload Processor B
  NODE_C: Payload Processor C
  GS: Ground Station
ax25:
  src_call: NOCALL
  src_ssid: 0
  dest_call: NOCALL
  dest_ssid: 0
csp:
  priority: 2
  source: 0
  destination: 8
  dest_port: 24
  src_port: 0
  flags: 0
  csp_crc: true
tx:
  zmq_addr: tcp://127.0.0.1:52002
  frequency: 437.000 MHz
  delay_ms: 500
  uplink_mode: AX.25
rx:
  zmq_port: 52001
  zmq_addr: tcp://127.0.0.1:52001
general:
  mission_name: MAVERIC
  version: 5.0.0
  log_dir: logs
  command_defs: maveric_commands.yml
  decoder_yml: maveric_decoder.yml
  gs_node: GS
  generated_commands_dir: generated_commands
  rx_title: MAVERIC Downlink
  tx_title: MAVERIC Uplink
  splash_subtitle: MAVERIC Ground Station
